Repository InnovaTech-arquitectura/front-admin, pull requests merged in 2024-10, with the labels that each got.

#47 Merge changes done for selenium testing
  .github/workflows/deployProduction.yml
  .github/workflows/deployTesting.yml
  Dockerfile
  angular.json
  deploy.sh
  docker-compose.yml
  nginx.conf
  package-lock.json
  src/app/bazares/crear-bazar/crear-bazar.component.html
  src/app/bazares/editar-bazar/editar-bazar.component.html
  src/app/bazares/editar-bazar/editar-bazar.component.ts
  src/app/bazares/ver-bazares/ver-bazares.component.html
  src/app/bazares/ver-bazares/ver-bazares.component.ts
  src/app/capacitaciones/crear-capacitaciones/crear-capacitaciones.component.html
  src/app/capacitaciones/editar-capacitaciones/editar-capacitaciones.component.html
  src/app/capacitaciones/ver-capacitaciones/ver-capacitaciones.component.html
  src/app/componentTools/sidebar/sidebar.component.html
  src/app/perfiles/perfil-editar-empleado/perfil-editar-empleado.component.html
  src/app/perfiles/perfil-nuevo-empleado/perfil-nuevo-empleado.component.html
  src/app/perfiles/perfil-tipo/perfil-tipo.component.html
  src/app/perfiles/ver-perfiles/ver-perfiles.component.html
  src/app/planes/crear-plan/crear-plan.component.html
  src/app/planes/editar-plan/editar-plan.component.html
  src/app/planes/ver-planes/ver-planes.component.html
  src/app/service/auth.service.ts
  src/app/service/capacitaciones.service.ts
  src/app/service/events.service.ts
  src/app/service/perfiles.service.ts
  src/app/service/planes.service.ts
  src/environments/environment.prod.ts
  src/environments/environment.testing.ts
  src/environments/environment.ts
Labels: enhancement

#48 Merge fixes for screens
  src/app/bazares/crear-bazar/crear-bazar.component.html
  src/app/bazares/editar-bazar/editar-bazar.component.html
  src/app/bazares/editar-bazar/editar-bazar.component.ts
  src/app/bazares/ver-bazares/ver-bazares.component.html
  src/app/bazares/ver-bazares/ver-bazares.component.ts
  src/app/capacitaciones/crear-capacitaciones/crear-capacitaciones.component.html
  src/app/capacitaciones/editar-capacitaciones/editar-capacitaciones.component.html
  src/app/capacitaciones/ver-capacitaciones/ver-capacitaciones.component.html
  src/app/componentTools/sidebar/sidebar.component.html
  src/app/perfiles/perfil-editar-empleado/perfil-editar-empleado.component.html
  src/app/perfiles/perfil-nuevo-empleado/perfil-nuevo-empleado.component.html
  src/app/perfiles/perfil-tipo/perfil-tipo.component.html
  src/app/perfiles/ver-perfiles/ver-perfiles.component.html
  src/app/planes/crear-plan/crear-plan.component.html
  src/app/planes/editar-plan/editar-plan.component.html
  src/app/planes/ver-planes/ver-planes.component.html
  src/app/service/events.service.ts
Labels: bug, enhancement

#49 Bug profiles / user
  src/app/perfiles/perfil-editar-empleado/perfil-editar-empleado.component.ts
  src/app/perfiles/perfil-tipo/perfil-tipo.component.html
  src/app/perfiles/perfil-tipo/perfil-tipo.component.ts
Labels: bug

#50 Fix edit bug
  src/app/perfiles/perfil-tipo/perfil-tipo.component.html
Labels: bug

#56 Error handling plans & profiles
  src/app/perfiles/perfil-editar-empleado/perfil-editar-empleado.component.ts
  src/app/perfiles/perfil-nuevo-empleado/perfil-nuevo-empleado.component.ts
  src/app/perfiles/perfil-tipo/perfil-tipo.component.ts
  src/app/planes/crear-plan/crear-plan.component.ts
  src/app/planes/editar-plan/editar-plan.component.ts
  src/app/planes/ver-planes/ver-planes.component.ts
  src/app/service/perfiles.service.ts
  src/app/service/planes.service.ts
Labels: bug, enhancement

#62 feat coupons
  src/app/cupones/crear-cupon/crear-cupon.component.css
  src/app/cupones/crear-cupon/crear-cupon.component.html
  src/app/cupones/crear-cupon/crear-cupon.component.ts
  src/app/cupones/editar-cupon/editar-cupon.component.css
  src/app/cupones/editar-cupon/editar-cupon.component.html
  src/app/cupones/editar-cupon/editar-cupon.component.spec.ts
  src/app/cupones/editar-cupon/editar-cupon.component.ts
  src/app/cupones/ver-cupones/ver-cupones.component.html
  src/app/cupones/ver-cupones/ver-cupones.component.spec.ts
  src/app/cupones/ver-cupones/ver-cupones.component.ts
  src/app/model/coupon.ts
  src/app/model/newCoupon.ts
  src/app/planes/ver-planes/ver-planes.component.css
  src/app/planes/ver-planes/ver-planes.component.html
  src/app/service/cupones.service.ts
  src/styles.css
Labels: enhancement

#66 Fixes
  src/app/componentTools/header/header.component.css
  src/app/componentTools/sidebar/sidebar.component.css
  src/app/componentTools/sidebar/sidebar.component.html
  src/app/cupones/ver-cupones/ver-cupones.component.html
  src/app/inicio-sesion/inicio-sesion.component.ts
  src/app/planes/crear-plan/crear-plan.component.ts
Labels: bug, enhancement

#74 Sidebar changing on role and PQRS
  src/app/app-routing.module.ts
  src/app/componentTools/sidebar/sidebar.component.html
  src/app/componentTools/sidebar/sidebar.component.spec.ts
  src/app/componentTools/sidebar/sidebar.component.ts
  src/app/inicio-sesion/inicio-sesion.component.ts
  src/app/planes/crear-plan/crear-plan.component.ts
  src/app/planes/editar-plan/editar-plan.component.ts
  src/app/service/auth.service.ts
  src/app/service/pqrs.service.spec.ts
  src/app/service/pqrs.service.ts
  src/app/soporte/responder-pregunta/responder-pregunta.component.html
  src/app/soporte/responder-pregunta/responder-pregunta.component.spec.ts
  src/app/soporte/responder-pregunta/responder-pregunta.component.ts
  src/app/soporte/soporte-principal/soporte-principal.component.html
  src/app/soporte/soporte-principal/soporte-principal.component.spec.ts
  src/app/soporte/soporte-principal/soporte-principal.component.ts
Labels: bug, enhancement

#78 Bug fix hermann
  src/app/componentTools/header/header.component.css
  src/app/dashboard/graphs/graphs.component.html
  src/app/dashboard/graphs/graphs.component.spec.ts
  src/app/dashboard/graphs/graphs.component.ts
  src/app/emprendimientos/stats-emprendimiento/stats-emprendimiento.component.html
  src/app/emprendimientos/stats-emprendimiento/stats-emprendimiento.component.spec.ts
  src/app/emprendimientos/stats-emprendimiento/stats-emprendimiento.component.ts
  src/app/emprendimientos/ver-emprendimeintos/ver-emprendimeintos.component.css
  src/app/inicio-sesion/inicio-sesion.component.ts
  src/app/planes/ver-planes/ver-planes.component.css
  src/app/planes/ver-planes/ver-planes.component.html
  src/app/service/dashboard.service.spec.ts
  src/app/service/dashboard.service.ts
Labels: enhancement

#82 Cambios a cupones
  src/app/cupones/crear-cupon/crear-cupon.component.css
  src/app/cupones/crear-cupon/crear-cupon.component.html
  src/app/cupones/editar-cupon/editar-cupon.component.css
  src/app/cupones/editar-cupon/editar-cupon.component.html
  src/app/cupones/editar-cupon/editar-cupon.component.ts
Labels: enhancement
