Repository InnovaTech-arquitectura/front-admin, pull requests merged in 2024-09, with the labels that each got.

#5 Create dependabot.yml
  .github/dependabot.yml
Labels: dependencies

#6 Create actionsConfig.yml
  .github/workflows/actionsConfig.yml
Labels: dependencies

#8 Update actionsConfig.yml
  .github/workflows/actionsConfig.yml
Labels: dependencies

#9 Branch de desarrollo
  .github/workflows/actionsConfig.yml
Labels: help wanted

#11 Mapu
  angular.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/capacitaciones/crear-capacitaciones/crear-capacitaciones.component.css
  src/app/capacitaciones/crear-capacitaciones/crear-capacitaciones.component.html
  src/app/capacitaciones/crear-capacitaciones/crear-capacitaciones.component.spec.ts
  src/app/capacitaciones/crear-capacitaciones/crear-capacitaciones.component.ts
  src/app/capacitaciones/editar-capacitaciones/editar-capacitaciones.component.css
  src/app/capacitaciones/editar-capacitaciones/editar-capacitaciones.component.html
  src/app/capacitaciones/editar-capacitaciones/editar-capacitaciones.component.spec.ts
  src/app/capacitaciones/editar-capacitaciones/editar-capacitaciones.component.ts
  src/app/capacitaciones/ver-capacitaciones/ver-capacitaciones.component.css
  src/app/capacitaciones/ver-capacitaciones/ver-capacitaciones.component.html
  src/app/capacitaciones/ver-capacitaciones/ver-capacitaciones.component.spec.ts
  src/app/capacitaciones/ver-capacitaciones/ver-capacitaciones.component.ts
  src/app/capacitaciones/ver-info-capacitaciones/ver-info-capacitaciones.component.css
  src/app/capacitaciones/ver-info-capacitaciones/ver-info-capacitaciones.component.html
  src/app/capacitaciones/ver-info-capacitaciones/ver-info-capacitaciones.component.spec.ts
  src/app/capacitaciones/ver-info-capacitaciones/ver-info-capacitaciones.component.ts
  src/app/componentTools/sidebar/sidebar.component.html
  src/app/recuperar-password/crear/crear.component.css
  src/app/recuperar-password/crear/crear.component.html
  src/app/recuperar-password/crear/crear.component.spec.ts
  src/app/recuperar-password/crear/crear.component.ts
  src/app/recuperar-password/recuperar/recuperar.component.css
  src/app/recuperar-password/recuperar/recuperar.component.html
  src/app/recuperar-password/recuperar/recuperar.component.spec.ts
  src/app/recuperar-password/recuperar/recuperar.component.ts
  src/app/recuperar-password/verificacion/verificacion.component.css
  src/app/recuperar-password/verificacion/verificacion.component.html
  src/app/recuperar-password/verificacion/verificacion.component.spec.ts
  src/app/recuperar-password/verificacion/verificacion.component.ts
  src/app/soporte/responder-pregunta/responder-pregunta.component.css
  src/app/soporte/responder-pregunta/responder-pregunta.component.html
  src/app/soporte/responder-pregunta/responder-pregunta.component.spec.ts
  src/app/soporte/responder-pregunta/responder-pregunta.component.ts
Labels: enhancement

#13 carga bazares y cupones
  angular.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/bazares/crear-bazar/crear-bazar.component.css
  src/app/bazares/crear-bazar/crear-bazar.component.html
  src/app/bazares/crear-bazar/crear-bazar.component.spec.ts
  src/app/bazares/crear-bazar/crear-bazar.component.ts
  src/app/bazares/detalles-bazar/detalles-bazar.component.css
  src/app/bazares/detalles-bazar/detalles-bazar.component.html
  src/app/bazares/detalles-bazar/detalles-bazar.component.spec.ts
  src/app/bazares/detalles-bazar/detalles-bazar.component.ts
  src/app/bazares/editar-bazar/editar-bazar.component.css
  src/app/bazares/editar-bazar/editar-bazar.component.html
  src/app/bazares/editar-bazar/editar-bazar.component.spec.ts
  src/app/bazares/editar-bazar/editar-bazar.component.ts
  src/app/bazares/ver-bazares/ver-bazares.component.css
  src/app/bazares/ver-bazares/ver-bazares.component.html
  src/app/bazares/ver-bazares/ver-bazares.component.spec.ts
  src/app/bazares/ver-bazares/ver-bazares.component.ts
  src/app/cupones/crear-cupon/crear-cupon.component.css
  src/app/cupones/crear-cupon/crear-cupon.component.html
  src/app/cupones/crear-cupon/crear-cupon.component.spec.ts
  src/app/cupones/crear-cupon/crear-cupon.component.ts
  src/app/cupones/editar-cupon/editar-cupon.component.css
  src/app/cupones/editar-cupon/editar-cupon.component.html
  src/app/cupones/editar-cupon/editar-cupon.component.spec.ts
  src/app/cupones/editar-cupon/editar-cupon.component.ts
  src/app/cupones/ver-cupones/ver-cupones.component.css
  src/app/cupones/ver-cupones/ver-cupones.component.html
  src/app/cupones/ver-cupones/ver-cupones.component.spec.ts
  src/app/cupones/ver-cupones/ver-cupones.component.ts
Labels: enhancement

#15 Incorporación Cambios
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/componentTools/bar-chart/bar-chart.component.css
  src/app/componentTools/bar-chart/bar-chart.component.html
  src/app/componentTools/bar-chart/bar-chart.component.spec.ts
  src/app/componentTools/bar-chart/bar-chart.component.ts
  src/app/componentTools/header/header.component.css
  src/app/componentTools/header/header.component.html
  src/app/componentTools/line-chart/line-chart.component.css
  src/app/componentTools/line-chart/line-chart.component.html
  src/app/componentTools/line-chart/line-chart.component.spec.ts
  src/app/componentTools/line-chart/line-chart.component.ts
  src/app/componentTools/pie-chart/pie-chart.component.css
  src/app/componentTools/pie-chart/pie-chart.component.html
  src/app/componentTools/pie-chart/pie-chart.component.spec.ts
  src/app/componentTools/pie-chart/pie-chart.component.ts
  src/app/componentTools/sidebar/sidebar.component.css
  src/app/componentTools/sidebar/sidebar.component.html
  src/app/finanzas/finanzas.component.css
  src/app/finanzas/finanzas.component.html
  src/app/finanzas/finanzas.component.spec.ts
  src/app/finanzas/finanzas.component.ts
  src/app/inicio-sesion/inicio-sesion.component.css
  src/app/inicio-sesion/inicio-sesion.component.html
  src/app/inicio-sesion/inicio-sesion.component.spec.ts
  src/app/inicio-sesion/inicio-sesion.component.ts
  src/app/publicidad/nuevo-banner/nuevo-banner.component.css
  src/app/publicidad/nuevo-banner/nuevo-banner.component.html
  src/app/publicidad/nuevo-banner/nuevo-banner.component.spec.ts
  src/app/publicidad/nuevo-banner/nuevo-banner.component.ts
  src/app/publicidad/ver-banners/ver-banners.component.css
  src/app/publicidad/ver-banners/ver-banners.component.html
  src/app/publicidad/ver-banners/ver-banners.component.spec.ts
  src/app/publicidad/ver-banners/ver-banners.component.ts
  tsconfig.json
Labels: enhancement

#23 Feat carga pantallas Dashboard, Stats Emp, Crear y Editar empleados
  angular.json
  package-lock.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/componentTools/bar-chart/bar-chart.component.css
  src/app/componentTools/sidebar/sidebar.component.html
  src/app/dashboard/graphs/graphs.component.css
  src/app/dashboard/graphs/graphs.component.html
  src/app/dashboard/graphs/graphs.component.spec.ts
  src/app/dashboard/graphs/graphs.component.ts
  src/app/emprendimientos/stats-emprendimiento/stats-emprendimiento.component.css
  src/app/emprendimientos/stats-emprendimiento/stats-emprendimiento.component.html
  src/app/emprendimientos/stats-emprendimiento/stats-emprendimiento.component.spec.ts
  src/app/emprendimientos/stats-emprendimiento/stats-emprendimiento.component.ts
  src/app/emprendimientos/ver-emprendimeintos/ver-emprendimeintos.component.css
  src/app/emprendimientos/ver-emprendimeintos/ver-emprendimeintos.component.html
  src/app/emprendimientos/ver-emprendimeintos/ver-emprendimeintos.component.spec.ts
  src/app/emprendimientos/ver-emprendimeintos/ver-emprendimeintos.component.ts
  src/app/perfiles/perfil-editar-empleado/perfil-editar-empleado.component.css
  src/app/perfiles/perfil-editar-empleado/perfil-editar-empleado.component.html
  src/app/perfiles/perfil-editar-empleado/perfil-editar-empleado.component.spec.ts
  src/app/perfiles/perfil-editar-empleado/perfil-editar-empleado.component.ts
  src/app/perfiles/perfil-nuevo-empleado/perfil-nuevo-empleado.component.css
  src/app/perfiles/perfil-nuevo-empleado/perfil-nuevo-empleado.component.html
  src/app/perfiles/perfil-nuevo-empleado/perfil-nuevo-empleado.component.spec.ts
  src/app/perfiles/perfil-nuevo-empleado/perfil-nuevo-empleado.component.ts
  src/app/perfiles/perfil-tipo/perfil-tipo.component.html
Labels: enhancement

#25 feat Realizada conexion con back. Autenticación de inicio de sesión y…
  src/app/componentTools/header/header.component.html
  src/app/componentTools/header/header.component.ts
  src/app/inicio-sesion/inicio-sesion.component.ts
  src/app/service/auth.service.ts
Labels: enhancement

#29 dependencies Configuracion para despliegue
  .github/workflows/deployTesting.yml
Labels: dependencies

#32 fix deployment para self-hosted runner en maquina virtual
  .github/workflows/deployTesting.yml
Labels: dependencies

#34 configuracion de automatización de despliegue
  .github/workflows/deployTesting.yml
  Dockerfile
  nginx.conf
Labels: bug, dependencies

#38 Feat conexión eventos
  src/app/bazares/crear-bazar/crear-bazar.component.html
  src/app/bazares/crear-bazar/crear-bazar.component.spec.ts
  src/app/bazares/crear-bazar/crear-bazar.component.ts
  src/app/bazares/detalles-bazar/detalles-bazar.component.html
  src/app/bazares/detalles-bazar/detalles-bazar.component.spec.ts
  src/app/bazares/detalles-bazar/detalles-bazar.component.ts
  src/app/bazares/editar-bazar/editar-bazar.component.html
  src/app/bazares/editar-bazar/editar-bazar.component.spec.ts
  src/app/bazares/editar-bazar/editar-bazar.component.ts
  src/app/bazares/ver-bazares/ver-bazares.component.html
  src/app/bazares/ver-bazares/ver-bazares.component.spec.ts
  src/app/bazares/ver-bazares/ver-bazares.component.ts
  src/app/componentTools/sidebar/sidebar.component.html
  src/app/model/events.ts
  src/app/service/events.service.spec.ts
  src/app/service/events.service.ts
Labels: enhancement

#39 Cargando capacitaciones
  package-lock.json
  src/app/app-routing.module.ts
  src/app/capacitaciones/crear-capacitaciones/crear-capacitaciones.component.html
  src/app/capacitaciones/crear-capacitaciones/crear-capacitaciones.component.spec.ts
  src/app/capacitaciones/crear-capacitaciones/crear-capacitaciones.component.ts
  src/app/capacitaciones/editar-capacitaciones/editar-capacitaciones.component.html
  src/app/capacitaciones/editar-capacitaciones/editar-capacitaciones.component.spec.ts
  src/app/capacitaciones/editar-capacitaciones/editar-capacitaciones.component.ts
  src/app/capacitaciones/ver-capacitaciones/ver-capacitaciones.component.html
  src/app/capacitaciones/ver-capacitaciones/ver-capacitaciones.component.spec.ts
  src/app/capacitaciones/ver-capacitaciones/ver-capacitaciones.component.ts
  src/app/capacitaciones/ver-info-capacitaciones/ver-info-capacitaciones.component.html
  src/app/capacitaciones/ver-info-capacitaciones/ver-info-capacitaciones.component.spec.ts
  src/app/capacitaciones/ver-info-capacitaciones/ver-info-capacitaciones.component.ts
  src/app/model/course.ts
  src/app/service/capacitaciones.service.spec.ts
  src/app/service/capacitaciones.service.ts
Labels: enhancement
